version: "3.9"
services:  
      postgres:
          image: postgres:9
          container_name: postgres
          environment: 
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=postgres
              - POSTGRES_DB=desafioVotacao
              - PGDATA=/var/lib/postgresql/data/desafioVotacao/
          ports:
            - "5431:5432"
          volumes:
            - desafioVotacao-volume:/var/lib/postgresql/data7
          networks:
            - backend
volumes:
    desafioVotacao-volume:

networks:
    backend:
